// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission6.Models;

namespace Mission6.Migrations
{
    [DbContext(typeof(MovieAppContext))]
    [Migration("20230213203521_nextone")]
    partial class nextone
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission6.Models.Movie", b =>
                {
                    b.Property<int>("movieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("movieID");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            movieID = 1,
                            Category = "Family",
                            Director = "Jennifer Yuh Nelson",
                            Edited = false,
                            LentTo = "Charlie",
                            Notes = "A favorite!",
                            Rating = "PG",
                            Title = "Kung Fu Panda 2",
                            Year = 2011
                        },
                        new
                        {
                            movieID = 2,
                            Category = "Comedy",
                            Director = "Sean Anders",
                            Edited = false,
                            LentTo = "Hugh",
                            Notes = "Very Clever",
                            Rating = "PG-13",
                            Title = "Spirited",
                            Year = 2022
                        },
                        new
                        {
                            movieID = 3,
                            Category = "Action/Adventure",
                            Director = "Ridley Scott",
                            Edited = false,
                            LentTo = "Sarah",
                            Notes = "very involved",
                            Rating = "PG-13",
                            Title = "The Martian",
                            Year = 2015
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
